[package]
name = "rustqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bincode = "1.3"
text-tables = "0.3.1"
